# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c384bf1a91c6035e1ecff847f672322fa72ab2cb6427bdb76b96c34dfa9bb7b9fc7ea6ad630d63ad570ce6f153465fc011d70bd626c25bbe03a7d56885c5d4d

test:
  secret_key_base: 56c1feb46c09c9bbe3ddf3bb13d65583844266c42a61d639f97a694c459dd1d4b8f21637eae109024d0a51d53c5a77ee3fac5ee21446602303d3e51f97e239a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
